import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Header from "@/app/component/Header";
import { Schibsted_Grotesk, League_Spartan } from "next/font/google";

import "@/styles/globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const schibsted = Schibsted_Grotesk({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-schibsted",
  display: "swap",
});

const league = League_Spartan({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-league",
  display: "swap",
});

export const viewport = {
  width: "device-width",
  initialScale: 1,
  maximumScale: 1,
  userScalable: "no",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${schibsted.variable} ${league.variable}  antialiased `}
      >
        <Header />
        {children}
      </body>
    </html>
  );
}
